on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset
jobs:
  appimage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        set -x
        sh -eux tools/prepare-appimage
        ARCH=$(uname -m) sh -eux tools/build-appimage
        assets=()
        for asset in $(find . -name '*.AppImage'); do
          assets+=("-a" "$asset")
          bname=$(basename "$asset")
          dname=$(dirname "$asset")
          (cd "$dname" && md5sum "$bname" > "${bname}.md5")
          (cd "$dname" && sha256sum "$bname" > "${bname}.sha256")
        done
        for asset in $(find . -name '*.md5'); do
          assets+=("-a" "$asset")
        done
        for asset in $(find . -name '*.sha256'); do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
